### ISSUE TITLE
Create RMarkdown template for RAP products

### ISSUE THREAD

**Issue by mattkerlogue** [ukgovdatascience/govstyle#29]
With rise of RAP usage, a template for Official Statistics RAP reports could be useful. Would then allow departments/agencies to customise key elements (e.g. logo, colour scheme) to departmental standards while also ensuring consistency in products. Could also help in deployment of RAP techniques more widely by reducing set-up time for stats teams.

**Comment by mattkerlogue** [comment]
Should also ensure accessibility, as per https://github.com/ukgovdatascience/rap_companion/issues/83

**Comment by mattkerlogue** [comment]
But need to discuss/consider scope of the `govstyle` package… initially intended as just some `ggplot2` extensions - should it be a more fully fledged package providing core/'official' styling.

**Comment by mattkerlogue** [comment]
For reference:
- ONS Style: https://style.ons.gov.uk
- GOV.UK Design System: https://design-system.service.gov.uk

**Comment by nacnudus** [comment]
Thanks @mattkerlogue for opening this fruitful issue.  I am closing it now that [govdown](https://github.com/ukgovdatascience/govdown) exists to produce standalone HTML and websites that look like GOV.UK.

PDF is [not recommended](https://gds.blog.gov.uk/2018/07/16/why-gov-uk-content-should-be-published-in-html-and-not-pdf/).  A workaround is to print-to-pdf from a browser, and I think the GOV.UK Design System bears in mind that people will do that.  Feel free to open an issue on govdown if you think there's more to do -- I haven't investigated [pagedown](https://github.com/rstudio/pagedown), for example.
